class CleanupDatabaseForGn < ActiveRecord::Migration[7.1]
  def up
    # Supprimer les foreign keys d'abord
    remove_foreign_key :apprentices, :pets if foreign_key_exists?(:apprentices, :pets)
    remove_foreign_key :building_pets, :buildings if foreign_key_exists?(:building_pets, :buildings)
    remove_foreign_key :building_pets, :pets if foreign_key_exists?(:building_pets, :pets)
    remove_foreign_key :buildings, :headquarters if foreign_key_exists?(:buildings, :headquarters)
    remove_foreign_key :buildings, :pets, column: :chief_pet_id if foreign_key_exists?(:buildings, :pets, column: :chief_pet_id)
    remove_foreign_key :crew_members, :ships if foreign_key_exists?(:crew_members, :ships)
    remove_foreign_key :defenses, :headquarters if foreign_key_exists?(:defenses, :headquarters)
    remove_foreign_key :enemy_skills, :enemies if foreign_key_exists?(:enemy_skills, :enemies)
    remove_foreign_key :enemy_skills, :skills if foreign_key_exists?(:enemy_skills, :skills)
    remove_foreign_key :equipments, :users if foreign_key_exists?(:equipments, :users)
    remove_foreign_key :headquarter_inventory_objects, :headquarters if foreign_key_exists?(:headquarter_inventory_objects, :headquarters)
    remove_foreign_key :headquarter_inventory_objects, :inventory_objects if foreign_key_exists?(:headquarter_inventory_objects, :inventory_objects)
    remove_foreign_key :headquarter_objects, :users if foreign_key_exists?(:headquarter_objects, :users)
    remove_foreign_key :pet_inventory_objects, :inventory_objects if foreign_key_exists?(:pet_inventory_objects, :inventory_objects)
    remove_foreign_key :pet_inventory_objects, :pets if foreign_key_exists?(:pet_inventory_objects, :pets)
    remove_foreign_key :pet_skills, :pets if foreign_key_exists?(:pet_skills, :pets)
    remove_foreign_key :pet_skills, :skills if foreign_key_exists?(:pet_skills, :skills)
    remove_foreign_key :pet_statuses, :pets if foreign_key_exists?(:pet_statuses, :pets)
    remove_foreign_key :pet_statuses, :statuses if foreign_key_exists?(:pet_statuses, :statuses)
    remove_foreign_key :pets, :statuses if foreign_key_exists?(:pets, :statuses)
    remove_foreign_key :ship_objects, :ships if foreign_key_exists?(:ship_objects, :ships)
    remove_foreign_key :ship_weapons, :ships if foreign_key_exists?(:ship_weapons, :ships)
    remove_foreign_key :ships, :groups if foreign_key_exists?(:ships, :groups)
    remove_foreign_key :ships, :ships, column: :parent_ship_id if foreign_key_exists?(:ships, :ships, column: :parent_ship_id)
    remove_foreign_key :ships_skills, :ships if foreign_key_exists?(:ships_skills, :ships)
    remove_foreign_key :ships_skills, :skills if foreign_key_exists?(:ships_skills, :skills)
    remove_foreign_key :skills, :caracs if foreign_key_exists?(:skills, :caracs)
    remove_foreign_key :sphero_skills, :skills if foreign_key_exists?(:sphero_skills, :skills)
    remove_foreign_key :sphero_skills, :spheros if foreign_key_exists?(:sphero_skills, :spheros)
    remove_foreign_key :spheros, :users if foreign_key_exists?(:spheros, :users)
    remove_foreign_key :user_caracs, :caracs if foreign_key_exists?(:user_caracs, :caracs)
    remove_foreign_key :user_caracs, :users if foreign_key_exists?(:user_caracs, :users)
    remove_foreign_key :user_skills, :skills if foreign_key_exists?(:user_skills, :skills)
    remove_foreign_key :user_skills, :users if foreign_key_exists?(:user_skills, :users)
    remove_foreign_key :user_statuses, :statuses if foreign_key_exists?(:user_statuses, :statuses)
    remove_foreign_key :user_statuses, :users if foreign_key_exists?(:user_statuses, :users)
    remove_foreign_key :users, :classe_persos if foreign_key_exists?(:users, :classe_persos)
    remove_foreign_key :users, :pets if foreign_key_exists?(:users, :pets)
    remove_foreign_key :users, :races if foreign_key_exists?(:users, :races)

    # Supprimer les tables inutiles
    drop_table :apprentices if table_exists?(:apprentices)
    drop_table :building_pets if table_exists?(:building_pets)
    drop_table :buildings if table_exists?(:buildings)
    drop_table :combat_actions if table_exists?(:combat_actions)
    drop_table :combat_states if table_exists?(:combat_states)
    drop_table :crew_members if table_exists?(:crew_members)
    drop_table :defenses if table_exists?(:defenses)
    drop_table :enemy_skills if table_exists?(:enemy_skills)
    drop_table :enemies if table_exists?(:enemies)
    drop_table :equipments if table_exists?(:equipments)
    drop_table :headquarter_inventory_objects if table_exists?(:headquarter_inventory_objects)
    drop_table :headquarter_objects if table_exists?(:headquarter_objects)
    drop_table :headquarters if table_exists?(:headquarters)
    drop_table :pet_inventory_objects if table_exists?(:pet_inventory_objects)
    drop_table :pet_skills if table_exists?(:pet_skills)
    drop_table :pet_statuses if table_exists?(:pet_statuses)
    drop_table :pets if table_exists?(:pets)
    drop_table :ship_objects if table_exists?(:ship_objects)
    drop_table :ship_weapons if table_exists?(:ship_weapons)
    drop_table :ships_skills if table_exists?(:ships_skills)
    drop_table :ships if table_exists?(:ships)
    drop_table :sphero_skills if table_exists?(:sphero_skills)
    drop_table :spheros if table_exists?(:spheros)
    drop_table :user_caracs if table_exists?(:user_caracs)
    drop_table :user_skills if table_exists?(:user_skills)
    drop_table :user_statuses if table_exists?(:user_statuses)
    drop_table :skills if table_exists?(:skills)
    drop_table :caracs if table_exists?(:caracs)
    drop_table :classe_persos if table_exists?(:classe_persos)
    drop_table :races if table_exists?(:races)
    drop_table :statuses if table_exists?(:statuses)

    # Nettoyer les colonnes inutiles de la table users
    remove_index :users, :race_id if index_exists?(:users, :race_id)
    remove_index :users, :classe_perso_id if index_exists?(:users, :classe_perso_id)
    remove_index :users, :pet_id if index_exists?(:users, :pet_id)

    remove_column :users, :hp_max if column_exists?(:users, :hp_max)
    remove_column :users, :hp_current if column_exists?(:users, :hp_current)
    remove_column :users, :shield_state if column_exists?(:users, :shield_state)
    remove_column :users, :shield_max if column_exists?(:users, :shield_max)
    remove_column :users, :shield_current if column_exists?(:users, :shield_current)
    remove_column :users, :race_id if column_exists?(:users, :race_id)
    remove_column :users, :classe_perso_id if column_exists?(:users, :classe_perso_id)
    remove_column :users, :xp if column_exists?(:users, :xp)
    remove_column :users, :total_xp if column_exists?(:users, :total_xp)
    remove_column :users, :robustesse if column_exists?(:users, :robustesse)
    remove_column :users, :homeopathie if column_exists?(:users, :homeopathie)
    remove_column :users, :patch if column_exists?(:users, :patch)
    remove_column :users, :echani_shield_state if column_exists?(:users, :echani_shield_state)
    remove_column :users, :echani_shield_current if column_exists?(:users, :echani_shield_current)
    remove_column :users, :echani_shield_max if column_exists?(:users, :echani_shield_max)
    remove_column :users, :luck if column_exists?(:users, :luck)
    remove_column :users, :pet_id if column_exists?(:users, :pet_id)
    remove_column :users, :pet_action_points if column_exists?(:users, :pet_action_points)
    remove_column :users, :hp_bonus if column_exists?(:users, :hp_bonus)
    remove_column :users, :active_injection if column_exists?(:users, :active_injection)
    remove_column :users, :active_implant if column_exists?(:users, :active_implant)
    remove_column :users, :vitesse if column_exists?(:users, :vitesse)
    remove_column :users, :notes if column_exists?(:users, :notes)
    remove_column :users, :sex if column_exists?(:users, :sex)
    remove_column :users, :age if column_exists?(:users, :age)
    remove_column :users, :height if column_exists?(:users, :height)
    remove_column :users, :weight if column_exists?(:users, :weight)
    remove_column :users, :dark_side_points if column_exists?(:users, :dark_side_points)
    remove_column :users, :cyber_points if column_exists?(:users, :cyber_points)
    remove_column :users, :junkie if column_exists?(:users, :junkie)
  end

  def down
    raise ActiveRecord::IrreversibleMigration, "Cette migration ne peut pas etre annulee - trop de donnees supprimees"
  end
end
